# pull official base image
FROM python:3.8-slim-buster

# create directory for the app user
RUN mkdir -p /home/app  \
    && addgroup --system app && adduser --system --group app

# set environment variables
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_DISABLE_VERSION_CHECK=on \
    POETRY_VERSION=1.2.0 \
    POETRY_HOME="/opt/poetry" \
    POETRY_NO_INTERACTION=1 \
    PATH=/usr/local/bin:$PATH \
    ENVIRONMENT=prod \
    TESTING=0 \
    HOME=/home/app \
    APP_HOME=/home/app/web

RUN mkdir $APP_HOME \
    && chown -R app:app $APP_HOME
WORKDIR $APP_HOME

# install system dependencies
RUN apt-get update \
    && apt-get -y install --no-install-recommends \
        netcat gcc postgresql \
    && pip install --no-cache-dir "poetry==$POETRY_VERSION" \
    && apt-get clean

# install python dependencies
WORKDIR /usr/src/app
COPY ./pyproject.toml ./poetry.lock ./
RUN poetry  config virtualenvs.create false \
    && poetry install --no-root

# add app
COPY . .

USER app
# run entrypoint.sh
CMD gunicorn --bind 0.0.0.0:$PORT app.main:app -k uvicorn.workers.UvicornWorker